### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by citec-47** [yegonkimutai/Portfolio-project#7]
# You have done a great job implementing this project👌✔
-we kindly suggest the card should be according to figma design.

**Comment by bilalrajput09** [comment]
**Good job so far everything looks good!** 

**### Suggestion**
-Please try to match their alignments, everything else looks good.
![Screenshot 2023-02-28 082236](https://user-images.githubusercontent.com/116716918/221783551-07a55545-94fd-466f-a3aa-f1b93a977869.png)

**Comment by fickryiman** [comment]
Use the responsive width for text paragraph is much better, i think.

![image](https://user-images.githubusercontent.com/116701353/221784367-d7316f23-c9ec-4bb0-a4f2-002135f8530c.png)
